### ISSUE TITLE
matplotlib version installed with engine does not work with pandas in experiments/generate_plots.py

### ISSUE THREAD

**Issue by d1lacy** [seldonian-toolkit/Experiments#3]
It seems that the engine has a requirement of matplotlib 3.5.1 which is what installed for me when I started my project in a new environment with no previous installation of matplotlib. When I tried to make plots in an experiment, there was an issue between my installation of pandas and matplotlib. I got an error "Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead" which seems to be from the version of matplotlib using indexing that is no longer supported in pandas. By upgrading matplotlib to 3.7.1 I no longer have this error. Might want to change the matplotlib version installed with the engine?

**Comment by austinhoag** [comment]
This issue was fixed in https://github.com/seldonian-toolkit/Experiments/commit/f942faa1f2806b63dbaeeb0cf7fdf5e52691f20c a few weeks ago so `git pull` will resolve it. If you used the PyPI method to install the package originally, then do `pip install --upgrade seldonian-experiments`.
